version: '3'

vars:
  AWS_ACCOUNT:
    sh: echo $(aws sts get-caller-identity --profile {{.profile | default "default"}} | jq -r .Account 2>/dev/null);
  REGION: ap-northeast-1


includes:
  back:
    taskfile: https://raw.githubusercontent.com/gsy0911/task/main/taskfile.docker.yml
    vars:
      DOCKERFILE_PATH: ./backend/Dockerfile
      IMAGE: zenn-example
      CONTAINER: zenn-backend-container
      AWS_ACCOUNT:
        sh: echo $(aws sts get-caller-identity --profile {{.profile | default "default"}} | jq -r .Account 2>/dev/null);
      REGION: ap-northeast-1
      LAMBDA_NAME: zenn-example-lambda-endpoint
      tag: backend
  front:
    taskfile: https://raw.githubusercontent.com/gsy0911/task/main/taskfile.docker.yml
    vars:
      DOCKERFILE_PATH: ./frontend/Dockerfile
      IMAGE: zenn-example
      CONTAINER: zenn-frontend-container
      AWS_ACCOUNT:
        sh: echo $(aws sts get-caller-identity --profile {{.profile | default "default"}} | jq -r .Account 2>/dev/null);
      REGION: ap-northeast-1
      LAMBDA_NAME: zenn-example-frontend-endpoint
      tag: frontend


tasks:
  default:
    cmds:
      - task -l --sort none
    silent: true

  format:
    desc: format with black
    cmds:
      - isort {{.MODULE_NAME}}
      - isort test
      - black .
    preconditions:
      - type python > /dev/null 2>&1

  deploy-backend:
    desc: deploy backend; e.g. $ deploy-backend
    cmds:
      - task login
      - task back:build
      - task back:push
      - task back:update-docker-lambda

  deploy-frontend:
    desc: deploy backend; e.g. $ deploy-frontend
    cmds:
      - task login
      - task front:build-arm64
      - task front:push
      - task front:update-docker-lambda

  login:
    desc: login to ECR
    cmds:
      - aws ecr get-login-password --region {{.REGION}} | docker login --username AWS --password-stdin {{.AWS_ACCOUNT}}.dkr.ecr.{{.REGION}}.amazonaws.com
