import type { Metadata } from "next";
import type { GetServerSidePropsContext } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@mantine/core/styles.css";
import { MantineProvider, ColorSchemeScript } from "@mantine/core";
import { NextAuthProviders } from "@/app/providers";

const inter = Inter({ subsets: ["latin"] });

export async function getServerSideProps({ req, res }: GetServerSidePropsContext) {
  const referer = req.headers.referer;
  console.log(`ref: ${referer}`);
  return {
    props: { primaryColor: "green" },
  };
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  primaryColor,
}: {
  children: React.ReactNode;
  primaryColor: string;
}) {
  return (
    <html lang="en">
      <head title={"zenn-app-router"}>
        <ColorSchemeScript />
      </head>
      <body className={inter.className}>
        <NextAuthProviders>
          <MantineProvider
            theme={{
              primaryColor,
            }}
          >
            <>
              {primaryColor}
              {children}
            </>
          </MantineProvider>
        </NextAuthProviders>
      </body>
    </html>
  );
}
